### ISSUE TITLE
Unable to Dispose multiple servers

### ISSUE THREAD

**Issue by ykeysergit** [hibri/HttpMock#43]
Works for two, but not for three...

at Kayak.KayakServerState.SetClosing() in h:\kayak\Kayak\Net\Server\KayakServerState.cs:line 88
   at Kayak.DefaultKayakServer.Close() in h:\kayak\Kayak\Net\Server\KayakServer.cs:line 63
   at Kayak.DefaultKayakServer.<Listen>b__0() in h:\kayak\Kayak\Net\Server\KayakServer.cs:line 58
   at Kayak.Disposable.Dispose() in h:\kayak\Kayak\Disposable.cs:line 19
   at HttpMock.HttpServer.Dispose() in 
System.InvalidOperationException : The server was closing.

**Comment by ykeysergit** [comment]
Unable to reproduce
