### ISSUE TITLE
Duplicate params in query string

### ISSUE THREAD

**Issue by ykeysergit** [hibri/HttpMock#49]
WithParams doesn't support dup query params. I couldn't find a workaround.

In QueryParamMatch, there is...
if (!String.Equals(requestQueryParams[queryParam.Key], queryParam.Value, StringComparison.OrdinalIgnoreCase)) {
					return false;
				}

Could you please change it such that it uses requestQueryParams.Values given a key? That way, it can support dup query params polymorphically.

In EndpointMatchingRule,
var requestQueryParams = valueCollection.AllKeys
				.Where(k => !string.IsNullOrEmpty(k))
				.ToDictionary(k => k, k => valueCollection[k]);

This seems to ignore dup query params when it does ToDictionary.

**Comment by ykeysergit** [comment]
Test code...

IHttpServer serverA = null;

            Dictionary<string, string> queryParams1 = new Dictionary<string, string>();
            queryParams1.Add("value", "1");

            Dictionary<string, string> queryParams2 = new Dictionary<string, string>();
            queryParams1.Add("value", "2");

            serverA = HttpMockRepository.At("http://localhost:9080");
            serverA.Stub(x => x.Get("/ping")).WithParams(new Dictionary<string,string>()).Return("ok").OK();
            serverA.Stub(x => x.Get("/ping")).WithParams(queryParams1).Return("ok").OK();
            serverA.Stub(x => x.Get("/ping")).WithParams(queryParams2).Return("ok").OK();

            var client = new RestClient("http://localhost:9080");
            var request = new RestRequest("ping", Method.GET);
            request.AddQueryParameter("value", "1");
            var resp = client.Execute(request);

            resp.Content.Should().Contain("ok");

            serverA = serverA.WithNewContext();
            serverA.Stub(x => x.Get("/ping")).Return("ok").OK();
            serverA.Stub(x => x.Get("/ping")).WithParams(queryParams1).Return("ok").OK();
            serverA.Stub(x => x.Get("/ping")).WithParams(queryParams2).Return("ok").OK();

            request = new RestRequest("ping", Method.GET);
            request.AddQueryParameter("value", "1");
            resp = client.Execute(request);
            resp.Content.Should().Contain("ok");

            serverA.Dispose();

Result:

Result StackTrace:	
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Tests.UnitTest1.TestHttpMockWithNewContextWithDifferentQueryParams() in C:\Users\ykeyser\Source\Workspaces\PHS\Research\TestingTools\Tests\UnitTest1.cs:line 202
Result Message:	System.ArgumentException : An item with the same key has already been added.

**Comment by ykeysergit** [comment]
Test code...

            IHttpServer serverA = null;

            Dictionary<string, string> queryParams1 = new Dictionary<string, string>();
            queryParams1.Add("value", "1");

            Dictionary<string, string> queryParams2 = new Dictionary<string, string>();
            queryParams2.Add("value", "2");

            serverA = HttpMockRepository.At("http://localhost:9080");
            serverA.Stub(x => x.Get("/ping")).WithParams(new Dictionary<string,string>()).Return("{}").OK();
            serverA.Stub(x => x.Get("/ping")).WithParams(queryParams1).Return("ok").OK();
            serverA.Stub(x => x.Get("/ping")).WithParams(queryParams2).Return("ok").OK();

            var client = new RestClient("http://localhost:9080");

            var request = new RestRequest("ping", Method.GET);
            request.AddQueryParameter("value", "1");
            var resp = client.Execute(request);
            resp.Content.Should().Contain("ok");

            request = new RestRequest("ping", Method.GET);
            request.AddQueryParameter("value", "2");
            resp = client.Execute(request);
            resp.Content.Should().Contain("ok");

            request = new RestRequest("ping", Method.GET);
            resp = client.Execute(request);
            resp.Content.Should().Contain("{}");

            serverA = serverA.WithNewContext();
            serverA.Stub(x => x.Get("/ping")).WithParams(new Dictionary<string,string>()).Return("ok").OK();
            serverA.Stub(x => x.Get("/ping")).WithParams(queryParams1).Return("ok").OK();
            serverA.Stub(x => x.Get("/ping")).WithParams(queryParams2).Return("ok").OK();

            request = new RestRequest("ping", Method.GET);
            resp = client.Execute(request);
            resp.Content.Should().Contain("{}");

            request = new RestRequest("ping", Method.GET);
            request.AddQueryParameter("value", "1");
            resp = client.Execute(request);
            resp.Content.Should().Contain("ok");

            request = new RestRequest("ping", Method.GET);
            request.AddQueryParameter("value", "2");
            resp = client.Execute(request);

            resp.Content.Should().Contain("ok");

            serverA.Dispose();



Result StackTrace:	
at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net40\Execution\TestFrameworkProvider.cs:line 42
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\DefaultAssertionStrategy.cs:line 25
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringAssertions.Contain(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 620
   at Tests.UnitTest1.TestHttpMockWithNewContextWithDifferentQueryParams() in C:\Users\ykeyser\Source\Workspaces\PHS\Research\TestingTools\Tests\UnitTest1.cs:line 213
Result Message:	Expected string "{}" to contain "ok".

**Comment by ykeysergit** [comment]
IHttpServer serverA = null;

            Dictionary<string, string> queryParams1 = new Dictionary<string, string>();
            queryParams1.Add("value", "1");

            Dictionary<string, string> queryParams2 = new Dictionary<string, string>();
            queryParams2.Add("value", "2");

            serverA = HttpMockRepository.At("http://localhost:9080");
            serverA.Stub(x => x.Get("/ping")).WithParams(new Dictionary<string,string>()).Return("{}").OK();
            serverA.Stub(x => x.Get("/ping")).WithParams(queryParams1).Return("1").OK();
            serverA.Stub(x => x.Get("/ping")).WithParams(queryParams2).Return("2").OK();

            var client = new RestClient("http://localhost:9080");

            var request = new RestRequest("ping", Method.GET);
            request.AddQueryParameter("value", "1");
            var resp = client.Execute(request);
            resp.Content.Should().Contain("1");

            request = new RestRequest("ping", Method.GET);
            request.AddQueryParameter("value", "2");
            resp = client.Execute(request);
            resp.Content.Should().Contain("2");

            request = new RestRequest("ping", Method.GET);
            resp = client.Execute(request);
            resp.Content.Should().Contain("{}");

            serverA = serverA.WithNewContext();
            serverA.Stub(x => x.Get("/ping")).WithParams(new Dictionary<string,string>()).Return("ok").OK();
            serverA.Stub(x => x.Get("/ping")).WithParams(queryParams1).Return("ok").OK();
            serverA.Stub(x => x.Get("/ping")).WithParams(queryParams2).Return("ok").OK();

            request = new RestRequest("ping", Method.GET);
            resp = client.Execute(request);
            resp.Content.Should().Contain("{}");

            request = new RestRequest("ping", Method.GET);
            request.AddQueryParameter("value", "1");
            resp = client.Execute(request);
            resp.Content.Should().Contain("1");

            request = new RestRequest("ping", Method.GET);
            request.AddQueryParameter("value", "2");
            resp = client.Execute(request);

            resp.Content.Should().Contain("2");

            serverA.Dispose();

**Comment by ykeysergit** [comment]
IHttpServer serverA = null;

            Dictionary<string, string> queryParams1 = new Dictionary<string, string>();
            queryParams1.Add("value", "1");
            queryParams1.Add("value2", "11");

            Dictionary<string, string> queryParams2 = new Dictionary<string, string>();
            queryParams2.Add("value", "2");

            serverA = HttpMockRepository.At("http://localhost:9080");
            serverA.Stub(x => x.Get("/ping")).WithParams(queryParams1).Return("1").OK();
            serverA.Stub(x => x.Get("/ping")).WithParams(queryParams2).Return("2").OK();

            var client = new RestClient("http://localhost:9080");

            var request = new RestRequest("ping", Method.GET);
            request.AddQueryParameter("value", "2");
            var resp = client.Execute(request);
            resp.Content.Should().Contain("2");

            request = new RestRequest("ping", Method.GET);
            request.AddQueryParameter("value2", "11");
            request.AddQueryParameter("value", "2");
            resp = client.Execute(request);
            resp.Content.Should().Contain("1");

            serverA.Dispose();
